headless = true
address = "0.0.0.0"
port = 5000
[browser]
gatherUsageStats = false
[theme]
primaryColor = "#3366ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#fafafa"
font = "sans serif"
